<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>NuevoMMO Editor</AssemblyName>
    <RootNamespace>NuevoMMO.Editor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NuevoMMO.Editor/NuevoMMO.Editor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
  </ItemGroup>

</Project>
