<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>NuevoMMO.Server</AssemblyName>
    <RootNamespace>NuevoMMO.Server</RootNamespace>
    <UseAppHost>true</UseAppHost>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Core/NuevoMMO.Core/NuevoMMO.Core.csproj" />
    <ProjectReference Include="../../Network/NuevoMMO.Network/NuevoMMO.Network.csproj" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.11" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
    <PackageReference Include="Npgsql" Version="8.0.8" />
    <Compile Include="../Fixtures/**/*.cs" Link="Fixtures/%(RecursiveDir)%(Filename)%(Extension)" />
    <None Include="../Fixtures/*.json" Link="Fixtures/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="Database/Migrations/*.sql" />
  </ItemGroup>
</Project>
